	SYS_EXIT                = 60
	SYS_OPEN                = 2
	SYS_READ                = 0
	SYS_STATFS              = 137
	SYS_SYSINFO             = 99
	SYS_UNAME               = 63
	SYS_WRITE               = 1
	UTSNAME_SIZE            = 65

	open_paren_label:       .ascii " ("
	close_paren_label:      .ascii ")\n"
	data_number_label_0:    .ascii " GiB / "
	data_number_label_1:    .ascii " GiB ("
	data_number_label_2:    .ascii ")\n"
