	SYS_EXIT                = 60
	SYS_OPEN                = 2
	SYS_READ                = 0
	SYS_STATFS              = 137
	SYS_SYSINFO             = 99
	SYS_UNAME               = 63
	SYS_WRITE               = 1
	UTSNAME_SIZE            = 65

	close_paren_label:      .ascii ")\n"
	open_paren_label:       .ascii " ("
	size_label_0:           .ascii " GiB / "
	size_label_1:           .ascii " GiB ("
	size_label_2:           .ascii ")\n"
	unknown_label: .ascii "Unknown"
